#!/bin/bash
#
# check push pall with spaces

montyfile="./bytecodes/000.m"
correct="./expected/000.txt"

# send commands
./monty $montyfile > $OUTPUTFILE 2> $ERROROUTPUTFILE &
cat $correct > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

#error
print_error

# clean up
stop_monty
