#!/bin/bash
#
# check push pall with spaces and newlines with no opcode

montyfile="./bytecodes/001.m"
correct="./expected/001.txt"

# send commands
./monty $montyfile > $OUTPUTFILE 2> $ERROROUTPUTFILE &
cat $correct > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

#error
print_error

# clean up
stop_monty
