#!/bin/bash
#
# check push no arguments

montyfile="./bytecode-fails/fail-push-no-args.m"
correct="./expected-fails/fail-push-no-args.txt"

# send commands
./monty $montyfile > $ERROROUTPUTFILE 2> $OUTPUTFILE &
cat $correct > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

#error
#print_error

# clean up
stop_monty
