#!/bin/bash
#
# checks monty for no input file

correct="./expected-fails/fail-noinput.txt"

# send commands
./monty > $ERROROUTPUTFILE 2> $OUTPUTFILE &
cat $correct > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

#error
#print_error

# clean up
stop_monty
