#!/bin/bash
#
# check fail multiplication no args

montyfile="./bytecode-fails/fail-mul-noargs.m"
correct="./expected-fails/fail-mul-noargs.txt"

# send commands
./monty $montyfile > $ERROROUTPUTFILE > $OUTPUTFILE &
cat $correct > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

#error
#print_error

# clean up
stop_monty
