#!/bin/bash
#
# check fail division no arguments to divide

montyfile="./bytecode-fails/fail-div-noargs.m"
correct="./expected-fails/fail-div-noargs.txt"

# send commands
./monty $montyfile > $ERROROUTPUTFILE > $OUTPUTFILE &
cat $correct > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

#error
#print_error

# clean up
stop_monty
