#!/bin/bash
#
# check fail pop NULL stack

montyfile="./bytecode-fails/fail-pop-null-stack.m"
correct="./expected-fails/fail-pop-null-stack.txt"

# send commands
./monty $montyfile > $ERROROUTPUTFILE > $OUTPUTFILE &
cat $correct > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

#error
#print_error

# clean up
stop_monty
