#!/bin/bash
#
# check for failure to open file

montyfile="You_Should_Have_An_Error_Here!"
correct="./expected-fails/fail-open-file.txt"

# send commands
./monty $montyfile > $ERROROUTPUTFILE > $OUTPUTFILE &
cat $correct > $EXPECTED

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
check_diff

#error
#print_error

# clean up
stop_monty
